/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocalePlayersRouteImport } from './routes/$locale/players'
import { Route as LocaleGameModesRouteImport } from './routes/$locale/game-modes'
import { Route as LocaleGameRouteImport } from './routes/$locale/game'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePlayersRoute = LocalePlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGameModesRoute = LocaleGameModesRouteImport.update({
  id: '/game-modes',
  path: '/game-modes',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGameRoute = LocaleGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/game': typeof LocaleGameRoute
  '/$locale/game-modes': typeof LocaleGameModesRoute
  '/$locale/players': typeof LocalePlayersRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/game': typeof LocaleGameRoute
  '/$locale/game-modes': typeof LocaleGameModesRoute
  '/$locale/players': typeof LocalePlayersRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/game': typeof LocaleGameRoute
  '/$locale/game-modes': typeof LocaleGameModesRoute
  '/$locale/players': typeof LocalePlayersRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/game'
    | '/$locale/game-modes'
    | '/$locale/players'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/game'
    | '/$locale/game-modes'
    | '/$locale/players'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/game'
    | '/$locale/game-modes'
    | '/$locale/players'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/players': {
      id: '/$locale/players'
      path: '/players'
      fullPath: '/$locale/players'
      preLoaderRoute: typeof LocalePlayersRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/game-modes': {
      id: '/$locale/game-modes'
      path: '/game-modes'
      fullPath: '/$locale/game-modes'
      preLoaderRoute: typeof LocaleGameModesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/game': {
      id: '/$locale/game'
      path: '/game'
      fullPath: '/$locale/game'
      preLoaderRoute: typeof LocaleGameRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleGameRoute: typeof LocaleGameRoute
  LocaleGameModesRoute: typeof LocaleGameModesRoute
  LocalePlayersRoute: typeof LocalePlayersRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleGameRoute: LocaleGameRoute,
  LocaleGameModesRoute: LocaleGameModesRoute,
  LocalePlayersRoute: LocalePlayersRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
